---
baseURL: "https://conn.cx/"
languageCode: "en-us"
title: "conn"
theme: "distinct"

taxonomies:
    tag: "tags"

canonifyURLs: true

menu:
    top: []

    side:
        - name: albums
          url: /albums

        - name: tags
          url: /tags
